var pentaclesInfo = {
  pentacles01: ["Ace of Pentacles",
                "Ace of Pentacles symbolises a new beginning in your financial situation and an opportunity to deepen your security.", 
                "Ace of Pentacles reversed indicates financial losses and decrease in security. There might have been anticipation in regards to increased income and wealth which are not becoming a reality."],
  pentacles02: ["Two of Pentacles",
                "Two of Pentacles symbolises juggling with finances. You might have income from more than one source. Two of Pentacles also indicates investing money into different projects, or bartering.", 
                "Two of Pentacles reversed indicates the seeker is unable to juggle the demands of life. He loses sight of his finances and practical aspects of life."],
  pentacles03: ["Three of Pentacles",
                "Three of Pentacles symbolises your work, especially where team work or listening to clients/customers are concerned. This is a positive card which indicates job satisfaction and taking pride in your work, but you must put in the effort to see results.", 
                "Three of Pentacles reversed indicates lack of quality in work performance."],
  pentacles04: ["Four of Pentacles",
                "Four of Pentacles symbolises the need for security and recognition in your life, to have control over your possession and to keep abundance and money increasing. This card shows stubbornness in the situation or in the querent.", 
                "Four of Pentacles reversed indicates lack of something solid and dependable. There is nothing really reliable to hold on to."],
  pentacles05: ["Five of Pentacles",
                "Five of Pentacles symbolises financial loss or hardship. It can also mean you are in a place where you feel there is no security and your health might be suffering. ", 
                "Five of Pentacles reversed indicates disorder and chaos. Not only is there no money, but there is also a lack of spirituality and friendship."],
  pentacles06: ["Six of Pentacles",
                "Six of Pentacles symbolises generosity towards those who has less than you. It can also mean receiving generosity from others.", 
                "Six of Pentacles reversed indicates a lack of generosity. There might be greediness rather than sharing of wealth."],
  pentacles07: ["Seven of Pentacles",
                "Seven of Pentacles symbolises a vision that will pay off in the future. You are planting the seeds so that you will be able to harvest a more secure and abundant future for yourself.", 
                "Seven of Pentacles reversed indicates impatience and moving forward before the time is ripe. This card reversed can also mean unemployment."],
  pentacles08: ["Eight of Pentacles",
                "Eight of Pentacles symbolise craftsmanship in regards to work. It can also mean doing an apprenticeship and/or learning a new skill.", 
                "Eight of Pentacles reversed indicates tedious work with little gains. The seeker might be overdue for a promotion they deserve but are not getting."],
  pentacles09: ["Nine of Pentacles",
                "Nine of Pentacles symbolises luxury, financial security and being on a lavish holiday.", 
                "Nine of Pentacles reversed indicates loneliness and unhappiness. The home is neither secure nor very comfortable. The seeker might feel like a prisoner in their own home."],
  pentacles10: ["Ten of Pentacles",
                "Ten of Pentacles symbolises the type of wealth you get when you inherit something, being it your own retirement money, hand me downs, or possessions from someone who has passes away. ", 
                "Ten of Pentacles reversed indicates fortunes or legacies wasted or lost, or on a lesser note, delayed. There might be restrictive ties that become a burden."],
  pentaclesPage: ["Page of Pentacles",
                "Page of Pentacles indicates reinventing yourself in some way. It often denotes an opportunity to start something new, whether it is a creative venture, studying, business or a new job offer. Page of pentacles is not yet an expert in the field of choice, but has a clear goal and dream to achieve.", 
                "Page of Pentacles reversed indicates issues with learning and problems with studies. It denotes wasted talents, unrealistic ambitions and/or intellectual snobbery."],
  pentaclesKnight: ["Knight of Pentacles",
                "Knight of Pentacles denotes being of service and doing the actual work (in contrast to Page of Pentacles who enjoys daydreaming about the idea rather than actual living it). Knight of Pentacles is comfortable with routine and is efficient and conservative.", 
                "Knight of Pentacles reversed indicates sloppiness, bitterness and envy. This is someone who is sucking up to those who can help them climb the ladder to wealth and success, but will do nothing for those who haven’t got money or connections."],
  pentaclesQueen: ["Queen of Pentacles",
                "Queen of Pentacles is someone with a down to earth and practical approach to life and situations. It is important to have work/home balance, in fact if you could work from home you probably would. This card takes enjoyment in material pleasures and success.", 
                "Queen of Pentacles reversed indicates poor taste and lack of sensitivity to other people’s needs."],
  pentaclesKing: ["King of Pentacles",
                "King of Pentacles symbolises a successful business man or a person in a manager position. This is a stable and authoritative character, who is hard-working and dependable.", 
                "King of Pentacles reversed indicates someone who is too conservative and who won’t take any chances. He is reluctant in making any changes in the way things are. He is likely to be a miser and a hoarder."],
}