var pentaclesInfo = {
  pentacles01: ["Ace of Pentacles",
                "", 
                ""],
  pentacles02: ["Two of Pentacles",
                "", 
                ""],
  pentacles03: ["Three of Pentacles",
                "", 
                ""],
  pentacles04: ["Four of Pentacles",
                "", 
                ""],
  pentacles05: ["Five of Pentacles",
                "", 
                ""],
  pentacles06: ["Six of Pentacles",
                "", 
                ""],
  pentacles07: ["Seven of Pentacles",
                "", 
                ""],
  pentacles08: ["Eight of Pentacles",
                "", 
                ""],
  pentacles09: ["Nine of Pentacles",
                "", 
                ""],
  pentacles10: ["Ten of Pentacles",
                "", 
                ""],
  pentaclesPage: ["Page of Pentacles",
                "", 
                ""],
  pentaclesKnight: ["Knight of Pentacles",
                "", 
                ""],
  pentaclesQueen: ["Queen of Pentacles",
                "", 
                ""],
  pentaclesKing: ["King of Pentacles",
                "", 
                ""],
}