var swordsInfo = {
  swords01: ["Ace of Swords",
                "Ace of swords is the card for a new thought and belief system. It is the potential of mental energy used to create clarity and often also justice.", 
                "Ace of Swords reversed indicates that the stirring of the aces is blocked. Ideas and communication are blocked."],
  swords02: ["Two of Swords",
                "Two of Swords is the card for compromise, passiveness, keeping the peace (as in not rocking the boat), stalemate, indecision and avoiding conflict.", 
                "Two of Swords reversed indicates conflicts are unavoidable and compromises are not reached. The querent might be exhibiting too much personality and creates drama just to have something to do."],
  swords03: ["Three of Swords",
                "Three of Swords denotes heartbreak. sorrow, pain and separation. Sometimes the separation is only temporary, other times it is final.", 
                "Three of Swords reversed indicates there is blocked grief stored in the person’s heart. The querent might be afraid of grieving and is internalising. "],
  swords04: ["Four of Swords",
                "Four of Swords is about rest and rejuvenation, getting enough sleep and taking time out to meditate.", 
                "Four of Swords reversed denotes restlessness and burn outs. Thoughts and beliefs interrupt the person from recuperating."],
  swords05: ["Five of Swords",
                "Five of Swords is the card for defeat and betrayal, conflict and unhealthy competition. Words will be hurtful, lies will be told and your weaknesses used against you.", 
                ""],
  swords06: ["Six of Swords",
                "", 
                ""],
  swords07: ["Seven of Swords",
                "", 
                ""],
  swords08: ["Eight of Swords",
                "", 
                ""],
  swords09: ["Nine of Swords",
                "", 
                ""],
  swords10: ["Ten of Swords",
                "", 
                ""],
  swordsPage: ["Page of Swords",
                "", 
                ""],
  swordsKnight: ["Knight of Swords",
                "", 
                ""],
  swordsQueen: ["Queen of Swords",
                "", 
                ""],
  swordsKing: ["King of Swords",
                "", 
                ""],
}