var wandsInfo = {
  wands01: ["Ace of Wands",
                "Ace of wands speaks of new beginnings. Be bold and start something new. Follow your inspiration. Ace of Wands speaks of births of all kinds; the birth of enterprises and job opportunities, and also the birth of a baby.", 
                "Ace of Wands reversed indicates that new beginnings are blocked. Ideas and enterprises do not take hold and there is little if any growth."],
  wands02: ["Two of Wands",
                "Two of Wands is about manifesting using the will and strength of your mind. You might have to weigh up your options before deciding on the one that is best for you.", 
                "Two of Wands reversed indicates difficulties in making a decision, possibly due to the fear of making the wrong choice."],
  wands03: ["Three of Wands",
                "Three of Wands is the card for writers, and writing jobs and freelancers. It is also the card that follows the manifesting the querent did in Two of Wand, and the querent has now lived a new and exciting opportunity or dream.", 
                "Three of Wands reversed indicates there is a delay in rewards and a delay in a payoff. The seeker might be out of their league, unable to cope with the demands."],
  wands04: ["Four of Wands",
                "Four of Wands is the card for harmony and developing on a larger scale, often expanding your living situation, and also being stronger connected to a community.", 
                "Four of Wands reversed indicates the foundation not laid or not ready."],
  wands05: ["Five of Wands",
                "Five of Wands is about standing up for what is important to you, even if it means meeting some opposition.", 
                "Five of Wands reversed indicates loss in individuality. There is a struggle to stand out among others equally talented."],
  wands06: ["Six of Wands",
                "Six of Wands is the card for popularity, progress, victory and success, self-confidence and getting what you want.", 
                "Six of Wands reversed indicates not getting the rewards that are owed, success delayed of even defeat."],
  wands07: ["Seven of Wands",
                "Seven of Wands denotes being defensive and putting up barriers and boundaries. You are protecting your point of view and your position.", 
                "Seven of Wands reversed indicates an inability to hold your ground, especially if it is not popular. There is a lack of defending oneself."],
  wands08: ["Eight of Wands",
                "Eight of Wands speaks of swift action and progress. It often shows up when there is a visitor coming, or when the querent is visiting someone.", 
                "Eight of Wands reversed indicates lack of energy and slowness, and things are not moving in the right direction. There might be poor time management and delays."],
  wands09: ["Nine of Wands",
                "Nine of Wands is the card for strength, courage, resilience and endurance. Never give up and never surrender.", 
                "Nine of Wands reversed indicates weakness and stubbornness rather than strength and willpower. There is a waste of energy or lack of energy to save something."],
  wands10: ["Ten of Wands",
                "Ten of Wands is the card for hard work and taking on more responsibility.", 
                "Ten of Wands reversed indicates fear of responsibilities, and incapability to keep on top of things. The seeker might be unmotivated and ready to walk away from their duties."],
  wandsPage: ["Page of Wands",
                "Page of Wands denotes an enthusiastic young person who is eager to explore and gain life experience.", 
                "Ppage of wands reversedage of Wands reversed indicates a bully and a mean-tempered person who likes to show off and is demanding attention."],
  wandsKnight: ["Knight of Wands",
                "Knight of Wands denotes a person who is travelling through life at a high-speed, living life in the fast lane. This is someone who will be the life of the party.", 
                "Knight of Wands reversed indicates a bully who wants to win at any costs. This is someone with acting talent who can turn his charm on and off and manipulate to get his way."],
  wandsQueen: ["Queen of Wands",
                "Queen of Wands denotes a warm, kind and passionate woman. She is goal oriented and determined. She is also a metaphysic who can use her mind both to create harmony and havoc.", 
                "Queen of Wands reversed indicates intimidation and domination. There is a lack of faith or even worse, faith in black magic and darkness."],
  wandsKing: ["King of Wands",
                "King of Wands denotes a married man who is a natural and charismatic leader. He has entrepreneurial skills and loves to run a new and exciting project.", 
                "King of Wands reversed indicates dictatorship. This is someone with a god complex and a bad temper, often very violent."],
}